version: "3.8"
services:
  postrges_nlw:
    container_name: postgres_nlw
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= mel679806
      - POSTGRESS_DB= pg_nlw